### ISSUE TITLE
No change in bookmark list

### ISSUE THREAD

**Issue by ghost** [akirak/bookmark-frecency.el#5]
I installed the package and added this to my dot emacs:

```
(bookmark-frecency-mode 1)
(setq bookmark-sort-flag 'last-modified)
```
I don't have dashboard installed.
If I invoke my `bookmark-bmenu-list` the list remains static and no changes are made to the order. Does the package only order if dashboard is installed?

**Comment by akirak** [comment]
@emacs-elements Unless you have visited at least one bookmark while the global mode is on, it is the same as sorting by modification time, i.e. recency. Did you visit a bookmark?

**Comment by ghost** [comment]
Yes, I did. I visited several.

**Comment by akirak** [comment]
@emacs-elements What Emacs version are you using? Is `bookmark-bmenu--revert` function using `bookmark-maybe-sort-alist` function to retrieve the bookmark records?

**Comment by ghost** [comment]
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)

Yes, it appears so:

```
(defun bookmark-bmenu--revert ()
  "Re-populate `tabulated-list-entries'."
  (let (entries)
    (dolist (full-record (bookmark-maybe-sort-alist))...

```

**Comment by akirak** [comment]
At least on my computer (Emacs head), `bookmark-frecency-mode` works, even on `bookmark-bmenu-list`. 

If you open your `bookmark-default-file`, does it contain `x-frecency-access-count` in some of the entries?

**Comment by ghost** [comment]
It's working now! Thanks for your help.

**Comment by akirak** [comment]
I'm glad that you have successfully used my package. If you have any problem, please feel free to open a ticket.

**Comment by emacs-elements** [comment]
I have created a brief video to showcase your new package:

https://youtube.com/shorts/fr4kqLSSy9Y?feature=share

**Comment by akirak** [comment]
@emacs-elements That's great, thanks! I can't believe someone has created a video for my package!

**Comment by emacs-elements** [comment]
It's my pleasure! It actually follows nicely on a recent video I did on Emacs Bookmarks. Take care and good luck!
